name: ./run_tests.sh

on:
  push:
  pull_request:
  workflow_dispatch:
  merge_group:

jobs:
  run_tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: clone
        uses: actions/checkout@v4

      - name: ./run_tests.sh
        run: ./run_tests.sh

